name: multi-env deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select deployment environment"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print Deployment Environment
        run: |
          echo "Deploying to environment: ${{ github.event.inputs.environment }}"
        
